# ==================================
# PostgreSQL Config
# ==================================
spring.datasource.url=jdbc:postgresql://localhost:5432/scaleDB
spring.datasource.username=marsol
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================
# SQL Init Script (para schema-init.sql)
# ==================================
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema-init.sql

# ==================================
# JPA Config (Hibernate)
# ==================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==================================
# Spring Boot Config
# ==================================
spring.application.name=balanza-app-web
# Perfil activo: (puede ser dev, prod, test)
spring.profiles.active=dev
# Puerto del servidor (por defecto 8080, pero configurable)
server.port=8080

# ==================================
# Logging Config (niveles de logs)
# ==================================
logging.level.org.springframework=DEBUG







